HOM-130: Buyer Demand Cronjob
HomesNZ/buyer-demand pull request #1
Opened 2022-10-28 01:17 UTC by haoyu-ma

2022-11-01 02:45 UTC, EugenRakhimov requested changes
I think it might work after a deep refactoring - instead of trying to query all properties from ES - query by buckets that we will use. It might worth to talk with @braydengosse how deep we want to have this buckets. I would say - go first  by bedrooms only up to 3, then bedrooms plus bathrooms. Also you need to query all suburb_ids first, and then request data by suburbs and buckets.

2022-11-01 02:45 UTC, EugenRakhimov commented on internal/client/elasticsearch/client.go
> +		Query(query)
I think if you do the right query, that's: suburb_id, bathrooms, bedrooms ...,  you can ask elastic search to do percentile https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-aggregations-metrics-percentile-aggregation.html and 50% percentile would be a median, so you will just need to read it, and then save

2022-11-09 09:43 UTC, EugenRakhimov commented on internal/client/elasticsearch/client.go
> +		return es.doSearch(ctx, query, from+len(searchResult.Hits.Hits), results)
Recursion here

2022-11-09 09:43 UTC, EugenRakhimov commented on internal/entity/map_item_es.go
> +				currentListings = MapItemESs{}
you don't need to do that , it will return empty initialised array if key not found 
https://go.dev/play/p/ubNLlQcTiiy

2022-11-09 09:43 UTC, EugenRakhimov commented on internal/entity/map_item_es.go
> +			if !ok {
you don't need to do that , it will return empty initialised array if key not found 
https://go.dev/play/p/ubNLlQcTiiy

2022-11-09 09:43 UTC, EugenRakhimov commented on internal/entity/map_item_es.go
> +			days := int64(math.Round(listingSoldDate.Sub(listingDate).Hours() / 24))
I suggest refactor it to make it a function of item, as well as part of previous code

2022-11-09 09:43 UTC, EugenRakhimov commented on internal/entity/map_item_es.go
> +		if item.PropertyState.Valid && item.PropertyState.ValueOrZero() == 2 &&
you can create a method on item IsItemSold and encapsulate knowledge about item inside the entity

2022-11-09 09:43 UTC, EugenRakhimov commented on internal/repository/address/repo.go
> +const allSuburbIDsQuery = `
We have a specific table where we store all suburbs, homes_external_data.nz_localities;

2022-11-09 09:43 UTC, EugenRakhimov commented on internal/service/buyer_demand.go
> +			bds, err := s.calculateBuyerDemands(ctx, id)
write to channel instead, then you don't need to use Lock/Unlock

2022-11-09 09:43 UTC, EugenRakhimov commented on internal/service/buyer_demand.go
> +	err = s.repos.BuyerDemand().Populate(ctx, buyerDemands)
there is no need to aggregate all buyer demands, and then run cycle to write it to database. You can write as you go 1 by one. also, here you made sure that one error will break whole process. If you write to database as soon as you get bds value above, you can avoid that.

2022-11-09 19:48 UTC, haoyu-ma commented on internal/service/buyer_demand.go
> +			bds, err := s.calculateBuyerDemands(ctx, id)
Actual I changed it from `chan` to `lock/unlock`. I run it on my local previously, it will stop the process, I will double check it.

2022-11-30 03:23 UTC, merged