HOM-138: Added latest stats endpoint for buyer demand
HomesNZ/buyer-demand pull request #2
Opened 2022-11-09 02:33 UTC by haoyu-ma

2022-11-09 09:53 UTC, EugenRakhimov requested changes
First things first, remove possibility of SQL injection

2022-11-09 09:53 UTC, EugenRakhimov commented on internal/handler/handlers.go
> +		handlers.AllowedMethods([]string{"GET", "PUT", "DELETE", "POST"}),
Do you allow any of that? I thought we will start with GET

2022-11-09 09:53 UTC, EugenRakhimov commented on internal/handler/handlers.go
> +	r.Handle("/stats/latest", stdChain.Then(handlers.MethodHandler{"GET": BuyerDemandLatestStats(log.WithField("handler", "BuyerDemandLatestStats"), s)}))
I believe we only suppose to return it to people who claimed home(hence - authorised)

2022-11-09 09:53 UTC, EugenRakhimov commented on internal/repository/buyer_demand/repo.go
> +		whereArray = append(whereArray, fmt.Sprintf("property_type = '%s'", propertyType.ValueOrZero()))
That's an SQL injection ability right here.

2022-11-09 09:53 UTC, EugenRakhimov commented on internal/repository/buyer_demand/repo.go
> +		whereArray = append(whereArray, fmt.Sprintf("suburb_id = %d", suburbID.ValueOrZero()))
If data is coming from user(which it is), using sprintf to create query deeply wrong. Postgres and other databases have $1, $2 params for a reason.

2022-11-09 09:53 UTC, EugenRakhimov commented on internal/repository/buyer_demand/repo.go
> +	if !suburbID.IsZero() {
So what happens when suburb is zero - from the looks of it, it will return random suburb. Should we have a situation and NZ-wide median for that? Might be worth checking with @braydengosse

2022-11-09 19:42 UTC, haoyu-ma commented on internal/repository/buyer_demand/repo.go
> +		whereArray = append(whereArray, fmt.Sprintf("suburb_id = %d", suburbID.ValueOrZero()))
If the value is null, the $1 is not working. `suburb_id = null` is not the same with `suburb_id is null`

2022-11-09 20:06 UTC, haoyu-ma commented on internal/repository/buyer_demand/repo.go
> +		whereArray = append(whereArray, fmt.Sprintf("suburb_id = %d", suburbID.ValueOrZero()))
Oh, I still can use suburb `$1` ...

2022-11-10 20:40 UTC, haoyu-ma commented on internal/service/stats.go
> +	isOwner, err := s.repos.PropertyClaim().IsClaimedByUserID(ctx, req.PropertyID, req.UserID)
After claimed the property, we need give `property-rebuild-service` some seconds to refresh ES. So we have to check isOwner from DB instead of checking it from ES.

2022-11-22 03:08 UTC, merged